### ISSUE TITLE
Recent Apps crashes the app

### ISSUE THREAD

**Issue by AdamTMalek** [AdamTMalek/HWUTimetable#21]
When the "Recent Apps" button is clicked inside the timetable view, the app crashes with the following:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.hwutimetable, PID: 31995
    java.lang.RuntimeException: Parcel: unable to marshal value com.example.hwutimetable.parser.ItemType@3d95d87
        at android.os.Parcel.writeValue(Parcel.java:1664)
        at com.example.hwutimetable.parser.TimetableItem.writeToParcel(Unknown Source:27)
        at com.example.hwutimetable.parser.TimetableDay.writeToParcel(Unknown Source:40)
        at android.os.Parcel.writeParcelable(Parcel.java:1683)
        at android.os.Parcel.writeValue(Parcel.java:1589)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
        at android.os.Bundle.writeToParcel(Bundle.java:1233)
        at android.os.Parcel.writeBundle(Parcel.java:915)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:167)
        at android.os.Parcel.writeTypedObject(Parcel.java:1516)
        at android.os.Parcel.writeTypedList(Parcel.java:1395)
        at android.os.Parcel.writeTypedList(Parcel.java:1380)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
        at android.os.Parcel.writeParcelable(Parcel.java:1683)
        at android.os.Parcel.writeValue(Parcel.java:1589)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
        at android.os.Bundle.writeToParcel(Bundle.java:1233)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4008)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Opening "Recent Apps" on the main activity works as it should - it's only the timetable view.

**Comment by AdamTMalek** [comment]
Fixed in #26
